name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Ejecutar mi acción
        uses: ./.github/actions/my-action
        with:
          mensaje: 'Hola desde el workflow principal'
