name: Reusable Workflow

on:
  workflow_call:
    inputs:
      username:
        description: 'A username to greet'
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Print Greeting
        run: echo "Hello, ${{ inputs.username }}!"
